// Generated by scripts/art.ts — run `npm run art` after adding files.
// Names, not paths: the extension is resolved from ART_FILES.
//
// The ?v= is the first eight characters of the file's sha1, and it is the
// reason replacing a picture under its own name reaches anybody. Same name
// means same URL means every browser and every CDN keeps serving the copy it
// already has — locally that is one hard refresh, in production it is every
// visitor who ever opened the card, and the maker is the last person to see
// it because his own browser refetched days ago. New bytes, new URL.
//
// It also gives a swapped picture somewhere to show up: public/art is
// gitignored, so without this a replaced image changes nothing under version
// control at all.

export const ART_FILES: Record<string, string> = {};
