// Generated by scripts/art.ts — run `npm run art` after adding files.
// Names, not paths: the extension is resolved from ART_FILES.
//
// The ?v= is the first eight characters of the file's sha1, and it is the
// reason replacing a picture under its own name reaches anybody. Same name
// means same URL means every browser and every CDN keeps serving the copy it
// already has — locally that is one hard refresh, in production it is every
// visitor who ever opened the card, and the maker is the last person to see
// it because his own browser refetched days ago. New bytes, new URL.
//
// It also gives a swapped picture somewhere to show up: public/art is
// gitignored, so without this a replaced image changes nothing under version
// control at all.

export const ART_FILES: Record<string, string> = {
  "airdrop-season": "/art/airdropseason.webp?v=00fcf0d7",
  "ape-in": "/art/ape-in.webp?v=05dc1e7f",
  "bear-market": "/art/bearmarket.webp?v=f1a59093",
  "black-swan": "/art/blackswan.webp?v=3292e3e6",
  "bull-run": "/art/bullrun.webp?v=13f58bc5",
  "bundle": "/art/bundle.webp?v=0ab8e75d",
  "buy-the-dip": "/art/buy-the-dip.webp?v=7d76a921",
  "cabal-call": "/art/cabalcall.webp?v=2bebcdd2",
  "cabal-exit": "/art/cabalexit.webp?v=0bf87402",
  "cancelled": "/art/cancelled.webp?v=a1eb0747",
  "cex-listing": "/art/cex-listing.webp?v=34d7e900",
  "cto": "/art/communitytakeover.webp?v=40e76e17",
  "coordinated-dump": "/art/coordinateddump.webp?v=2fc79b5a",
  "copy-trade": "/art/copy-trade.webp?v=8b9ce4a8",
  "dev-sells": "/art/devsell.webp?v=bbe71854",
  "diamond-hands": "/art/diamondhands.webp?v=81eb8bb5",
  "elon-posts": "/art/elon-post.webp?v=35c969c1",
  "etf-approval": "/art/etfapproval.webp?v=f7f448f1",
  "exit-liquidity": "/art/exitliquidity.webp?v=4de414e6",
  "fomo": "/art/fomo.webp?v=9938d637",
  "ftx-collapse": "/art/ftxcollapse.webp?v=bfc4921e",
  "fud": "/art/fud.webp?v=222a53f1",
  "gas-war": "/art/gaswar.webp?v=dcf5a0f5",
  "graduation": "/art/graduation.webp?v=e116634d",
  "green-day": "/art/greenday.webp?v=4cbc3384",
  "insider-wallet": "/art/insiderwallet.webp?v=ebad91be",
  "jeet": "/art/jeet.webp?v=24af5081",
  "liquidation-cascade": "/art/liquidationcascade.webp?v=3e9badcb",
  "unfollowed": "/art/massunfollow.webp?v=abf5ff5a",
  "network-outage": "/art/networkoutage.webp?v=a41e82e6",
  "paper-hands": "/art/paperhands.webp?v=c3bb34b0",
  "profit-taking": "/art/profittaking.webp?v=4cd68314",
  "rebrand": "/art/rebrand.webp?v=dd28801c",
  "retail-arrives": "/art/retailarrives.webp?v=811b58f6",
  "rug-pull": "/art/rugpull.webp?v=b9e4732a",
  "mev-sandwich": "/art/sandwich.webp?v=5a36ffba",
  "second-wind": "/art/secondwind.webp?v=8f5a74f0",
  "shill": "/art/shill.webp?v=214ccf72",
  "sideways": "/art/sideways.webp?v=7675e525",
  "slippage": "/art/slippage.webp?v=2dbd96a8",
  "snipe": "/art/snipe.webp?v=487e6140",
  "supercycle": "/art/supercycle.webp?v=ea2c995f",
  "supply-shock": "/art/supplyshock.webp?v=73e7d014",
  "take-profit": "/art/takeprofit.webp?v=a697c342",
  "the-bottom": "/art/thebottom.webp?v=fc33d929",
  "exchange-hack": "/art/theexchangehack.webp?v=7171c8b2",
  "sol-flips-eth": "/art/theflippening.webp?v=327ed87c",
  "the-purge": "/art/thepurge.webp?v=a0704165",
  "rotation": "/art/therotation.webp?v=3d489871",
  "trench-warfare": "/art/trenchwarfare.webp?v=ae85d5ed",
  "volatility": "/art/volatility.webp?v=e263b202",
  "wallet-tracker": "/art/wallet-tracker.webp?v=788ee0d8",
  "whale-dump": "/art/whaledump.webp?v=c5a81736"
};
